theme: jekyll-theme-minimal
title: Welcome to our CSE 190 Project!
description: Our project is to optimize and change the whiteboards that are currently present in patient rooms such that information is more accessible and updated with the correct information to provide better care to the patients, and a better communication system. 
